"""Asset manifest: bind generated media (images / video / Canva design) to a reel.

The deployed Streamlit app and this repo's agent-driven generation are decoupled:
media is generated by a provider (a live MCP server in-session, or a REST API at
runtime) and the resulting URLs/paths are recorded in a small JSON manifest. The
UI reads the manifest to show real images in the 9:16 preview and thumbnail, and
to surface the Canva design link.

This keeps binary assets out of the repo (and works even where outbound asset
downloads are blocked) while still letting the preview render live media.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field, asdict
from typing import Any

DEFAULT_MANIFEST = os.path.join(os.path.dirname(os.path.dirname(__file__)), "samples", "sample_assets.json")


@dataclass
class AssetManifest:
    topic: str = ""
    generated_at: str = ""
    note: str = ""
    providers: dict[str, str] = field(default_factory=dict)
    thumbnail: dict[str, Any] = field(default_factory=dict)
    scenes: dict[str, Any] = field(default_factory=dict)  # keyed by scene number (str)
    canva: dict[str, Any] = field(default_factory=dict)

    # -- accessors ---------------------------------------------------------
    def scene_media_url(self, scene_number: int) -> str | None:
        entry = self.scenes.get(str(scene_number))
        return entry.get("url") if isinstance(entry, dict) else None

    def thumbnail_url(self) -> str | None:
        return self.thumbnail.get("url") or None

    def canva_edit_url(self) -> str | None:
        return self.canva.get("edit_url") or None

    def set_scene(self, scene_number: int, url: str, *, kind: str = "image",
                  provider: str = "manual", role: str = "") -> None:
        self.scenes[str(scene_number)] = {
            "kind": kind, "provider": provider, "role": role, "url": url,
        }

    def set_thumbnail(self, url: str, *, provider: str = "manual") -> None:
        self.thumbnail = {"kind": "image", "provider": provider, "url": url}

    # -- io ----------------------------------------------------------------
    def to_json(self) -> str:
        return json.dumps(asdict(self), indent=2, ensure_ascii=False)

    def save(self, path: str) -> None:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(self.to_json())


def load_manifest(path: str | None = None) -> AssetManifest:
    """Load a manifest; return an empty one if the file is missing/invalid."""
    path = path or DEFAULT_MANIFEST
    try:
        with open(path, encoding="utf-8") as fh:
            data = json.load(fh)
    except (OSError, json.JSONDecodeError):
        return AssetManifest()
    known = {f for f in AssetManifest.__dataclass_fields__}
    return AssetManifest(**{k: v for k, v in data.items() if k in known})
